musinjer/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('socios/', include('socios.urls')),
    path('', home, name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

socios/urls.py
from django.urls import path
from .views import socio_create_update,socio_detail,socio_delete,socio_list


app_name = 'socios'

urlpatterns = [
	path('new/', socio_create_update, name='socio_create'),
	path('edit/<int:socio_id>/', socio_create_update, name='socio_update'),
	path('detail/<int:socio_id>/', socio_detail, name='socio_detail'),
	path('delete/<int:socio_id>/', socio_delete, name='socio_delete'),
	path('list/', socio_list, name='socio_list'),
]

socios/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.utils import timezone

class Caracter(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Sexo(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class EstadoCivil(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Socio(models.Model):
    ESTADO_CHOICES = [
        ('A', 'Activo'),
        ('S', 'Suspendido'),
        ('B', 'Baja'),
    ]

    socio_id = models.IntegerField(primary_key=True)
    dni = models.IntegerField(unique=True, validators=[MaxValueValidator(999999999), MinValueValidator(1000000)])
    caracter = models.ForeignKey(Caracter, on_delete=models.SET_NULL, null=True)
    apellido = models.CharField(max_length=100)
    nombre = models.CharField(max_length=100)
    sexo = models.ForeignKey(Sexo, on_delete=models.SET_NULL, null=True)
    fec_nac = models.DateField(null=True, blank=True)
    estado_civil = models.ForeignKey(EstadoCivil, on_delete=models.SET_NULL, null=True)
    direccion = models.CharField(max_length=255, blank=True, null=True)
    localidad = models.CharField(max_length=100)
    celular = models.BigIntegerField(blank=True, null=True)
    telefono = models.BigIntegerField( blank=True, null=True)
    email = models.EmailField(unique=False)
    dependencia = models.CharField(max_length=100, blank=True, null=True)
    cargo = models.CharField(max_length=100, blank=True, null=True)
    funcion = models.CharField(max_length=100, blank=True, null=True)
    domicilio_laboral = models.CharField(max_length=255, blank=True, null=True)
    telefono_laboral = models.BigIntegerField( blank=True, null=True)
    estado= models.CharField(choices=ESTADO_CHOICES, default='A', blank=False,max_length=1)
    created_by = models.ForeignKey(User, related_name='socio_created_by', on_delete=models.SET_NULL, null=True)
    modified_by = models.ForeignKey(User, related_name='socio_modified_by', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    
    def __str__(self):
        return f"{self.apellido} {self.nombre}"

 
class Parentesco(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Grupo(models.Model):
   

    socio = models.ForeignKey(Socio, on_delete=models.CASCADE)
    dni_familiar = models.IntegerField()
    parentesco = models.ForeignKey(Parentesco, on_delete=models.SET_NULL, null=True)
    apellido_familiar = models.CharField(max_length=100)
    nombre_familiar = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.get_parentesco_display()} de {self.socio}"

socios/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Socio, Grupo


class SocioForm(forms.ModelForm):
    fec_nac = forms.DateField(
        required=False,
        label=False,
        widget=forms.DateInput(
            attrs={"class": "form-control form-control-sm", "type": "date"}
        ),
    )
    direccion = forms.CharField(
        required=False,
        label=False,
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}),
    )
    celular = forms.IntegerField(
        required=False,
        label=False,
        widget=forms.NumberInput(attrs={"class": "form-control form-control-sm"}),
    )
    telefono = forms.IntegerField(
        required=False,
        label=False,
        widget=forms.NumberInput(attrs={"class": "form-control form-control-sm"}),
    )
    email = forms.EmailField(
        required=False,
        label=False,
        widget=forms.EmailInput(attrs={"class": "form-control form-control-sm"}),
    )
    dependencia = forms.CharField(
        required=False,
        label=False,
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}),
    )
    cargo = forms.CharField(
        required=False,
        label=False,
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}),
    )
    funcion = forms.CharField(
        required=False,
        label=False,
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}),
    )
    domicilio_laboral = forms.CharField(
        required=False,
        label=False,
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}),
    )
    telefono_laboral = forms.IntegerField(
        required=False,
        label=False,
        widget=forms.NumberInput(attrs={"class": "form-control form-control-sm"}),
    )
    estado = forms.ChoiceField(
        required=False,
        label=False,
        choices=[
            ('A', 'Activo'),
            ('S', 'Suspendido'),
            ('B', 'Baja'),
        ],
        widget=forms.Select(attrs={"class": "form-select form-select-sm"}),
    )

    class Meta:
        model = Socio
        fields = "__all__"
        exclude = ['created_by', 'modified_by', 'created_at', 'updated_at']
        widgets = {
            "socio_id": forms.NumberInput(
                attrs={"class": "form-control form-control-sm"}
            ),
            "dni": forms.NumberInput(attrs={"class": "form-control form-control-sm"}),
            'caracter': forms.Select(attrs={'class': 'form-select form-select-sm'}),
            "apellido": forms.TextInput(
                attrs={"class": "form-control form-control-sm"}
            ),
            "nombre": forms.TextInput(attrs={"class": "form-control form-control-sm"}),
            'sexo': forms.Select(attrs={'class': 'form-select form-select-sm'}),
            'estado_civil': forms.Select(attrs={'class': 'form-select form-select-sm'}),
            "localidad": forms.TextInput(
                attrs={"class": "form-control form-control-sm"}
            ),
            "telefono": forms.NumberInput(
                attrs={"class": "form-control form-control-sm"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(SocioForm, self).__init__(*args, **kwargs)
        if self.data:  # Verifica si el formulario ha sido enviado
            for field_name, field in self.fields.items():
                if self.errors.get(field_name):
                    field.widget.attrs["class"] += " is-invalid"
                else:
                    field.widget.attrs["class"] += " is-valid"

    def clean_dni(self):
        dni = self.cleaned_data.get('dni')
        if Socio.objects.filter(dni=dni).exclude(pk=self.instance.pk).exists():
            raise ValidationError('El DNI ya existe.')
        return dni
        
    def clean_socio_id(self):
        socio_id = self.cleaned_data.get('socio_id')
        if Socio.objects.filter(socio_id=socio_id).exclude(pk=self.instance.pk).exists():
            raise ValidationError('El socio_id ya existe.')
        return socio_id
    
   


class GrupoForm(forms.ModelForm):
    class Meta:
        model = Grupo
        fields = "__all__"
        widgets = {
            "dni_familiar": forms.NumberInput(
                attrs={"class": "form-control form-control-sm"}
            ),
            'parentesco': forms.Select(attrs={'class': 'form-select form-select-sm'}),
            "apellido_familiar": forms.TextInput(
                attrs={"class": "form-control form-control-sm"}
            ),
            "nombre_familiar": forms.TextInput(
                attrs={"class": "form-control form-control-sm"}
            ),
        }


GrupoFormSet = inlineformset_factory(
    Socio, Grupo, form=GrupoForm, extra=1, can_delete=True
)

class FiltroSocioForm(forms.Form):
    socio_id = forms.IntegerField(
        required=False,
        label=False,
        widget=forms.NumberInput(attrs={"class": "form-control form-control-sm"}),
    )
    dni = forms.IntegerField(
        required=False,
        label=False,
        widget=forms.NumberInput(attrs={"class": "form-control form-control-sm"}),
    )
    apellido = forms.CharField(
        required=False,
        label=False,
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}),
    )
    nombre = forms.CharField(
        required=False,
        label=False,
        widget=forms.TextInput(attrs={"class": "form-control form-control-sm"}),
    )
    estado = forms.ChoiceField(
        required=False,
        label=False,
        choices=[
            ('', 'Seleccione un estado'),
            ('A', 'Activo'),
            ('S', 'Suspendido'),
            ('B', 'Baja'),
        ],
        widget=forms.Select(attrs={"class": "form-select form-select-sm"}),
    )

socios/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Socio
from .forms import SocioForm, GrupoFormSet, FiltroSocioForm
import openpyxl
from django.http import HttpResponse
from datetime import datetime
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required
def socio_create_update(request, socio_id=None):
    if socio_id:
        socio = get_object_or_404(Socio, pk=socio_id)
    else:
        socio = Socio()

    if request.method == 'POST':
        form = SocioForm(request.POST, instance=socio)
        formset = GrupoFormSet(request.POST, instance=socio)
        if form.is_valid() and formset.is_valid():
            try:
                socio.created_by = request.user
                socio = form.save()
                formset.instance = socio
                formset.save()
                return redirect('socios:socio_detail', socio_id=socio.socio_id)
            except IntegrityError:
                messages.error(request, 'El DNI o socio_id ya existe.')
        else:
            messages.error(request, 'Por favor corrige los errores en el formulario.')
    else:
        form = SocioForm(instance=socio)
        formset = GrupoFormSet(instance=socio)

    return render(request, 'socios.html', {'form': form, 'formset': formset})

@login_required
def socio_delete(request, socio_id):
    socio = get_object_or_404(Socio, pk=socio_id)
    socio.delete()
    return redirect(reverse('home'))

@login_required
def socio_detail(request, socio_id):
	socio = get_object_or_404(Socio, pk=socio_id)
	return render(request, 'socio_detail.html', {'socio': socio})

@login_required
def socio_list(request):
	form = FiltroSocioForm(request.GET)
	socios = Socio.objects.all()
	
	if request.GET and form.is_valid():
		if form.cleaned_data['socio_id']:
			socios = socios.filter(socio_id=form.cleaned_data['socio_id'])
		if form.cleaned_data['dni']:
			socios = socios.filter(dni=form.cleaned_data['dni'])
		if form.cleaned_data['apellido']:
			socios = socios.filter(apellido__icontains=form.cleaned_data['apellido'])
		if form.cleaned_data['nombre']:
			socios = socios.filter(nombre__icontains=form.cleaned_data['nombre'])
		if form.cleaned_data['estado']:
			socios = socios.filter(estado=form.cleaned_data['estado'])
	
	if request.GET.get('formato') == 'excel':
		workbook = openpyxl.Workbook()
		sheet = workbook.active
		sheet.title = 'Socios' + datetime.now().strftime('%Y%m%d')

		headers = ['Socio ID', 'DNI', 'Caracter', 'Apellido', 'Nombre', 'Sexo', 'Fecha de Nacimiento', 'Estado Civil', 'Dirección', 'Localidad', 'Celular', 'Teléfono', 'Email', 'Dependencia', 'Cargo', 'Función', 'Domicilio Laboral', 'Teléfono Laboral', 'Estado', 'Creado por', 'Modificado por', 'Fecha de Creación', 'Fecha de Actualización']
		sheet.append(headers)
		for socio in socios:
			row = [
				socio.socio_id,
				socio.dni,
				str(socio.caracter),  # Convertir a cadena de texto
				socio.apellido,
				socio.nombre,
				str(socio.sexo),  # Convertir a cadena de texto
				socio.fec_nac.strftime('%Y-%m-%d') if socio.fec_nac else '',
				str(socio.estado_civil),  # Convertir a cadena de texto
				socio.direccion,
				socio.localidad,
				socio.celular,
				socio.telefono,
				socio.email,
				socio.dependencia,
				socio.cargo,
				socio.funcion,
				socio.domicilio_laboral,
				socio.telefono_laboral,
				socio.estado,
				str(socio.created_by),  # Convertir a cadena de texto
				str(socio.modified_by),  # Convertir a cadena de texto
				socio.created_at.strftime('%Y-%m-%d %H:%M:%S') if socio.created_at else '',
				socio.updated_at.strftime('%Y-%m-%d %H:%M:%S') if socio.updated_at else ''
			]
			sheet.append(row)

		response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
		response['Content-Disposition'] = f'attachment; filename=socios-{datetime.now().strftime("%d")}-{datetime.now().strftime("%m")}-{datetime.now().strftime("%Y")}.xlsx'
		workbook.save(response)
		return response

	paginator = Paginator(socios, 10)
	page = request.GET.get('page')
	socios = paginator.get_page(page)

	return render(request, 'consulta.html', {'socios': socios, 'form': form})

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% block title %}
        <title>MUSINJER</title>
    {% endblock title %}
        
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
    

</head>
<body>
    
    {% if request.path != '/login/' %}
        
    <nav class="navbar navbar-expand-lg bg-body-tertiary rounded" aria-label="Thirteenth navbar example">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample11" aria-controls="navbarsExample11" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse d-lg-flex" id="navbarsExample11">
                <a class="navbar-brand col-lg-3 me-0" href="{% url "home" %}">MUSINJER</a>
                <ul class="navbar-nav col-lg-6 justify-content-lg-center">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'home' %}">INICIO</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "socios:socio_create" %}">NUEVO SOCIO</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'socios:socio_list' %}">CONSULTAS</a>
                    </li>
                    
                </ul>
                <div class="d-lg-flex col-lg-3 justify-content-lg-end">
                    {% if request.user.is_authenticated %}
                        <span class="navbar-text mx-3">
                            {{ request.user.username }}
                        </span>
                        <form action="{% url 'logout' %}" method="post" class="form-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-primary">Cerrar sesión</button>
                        </form>
                    {% else %}
                        <a class="btn btn-primary" href="{% url 'login' %}">Iniciar sesión</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    {% endif %}
    {% if request.path == '/' %}
    <div class="container ">
        <h3>Bienvenido {{ request.user.username }}</h3>
        <h6><span>Socios Activos:</span> {{active_members}}</h6>
        <h6><span>Socios Suspendidos:</span> {{suspended_members}}</h6>
        <h6><span>Socios de Baja:</span> {{inactive_members}}</h6>

    </div>
    <footer class="bg-body-tertiary text-center text-lg-start fixed-bottom">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2024 MUSINJER - desarrollado por Agustin Muller - contacto: agustinmuller98@gmail.com - 3624384200
        </div>
    </footer>
    {% endif %}
    {% block content %}
       
    {% endblock  %}
    <style>
        body {
            font-family: 'Inter', sans-serif;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

templates/consulta.html
{% extends 'base.html' %}


{% block title %}
    <title>Consultas</title>
{% endblock  %}


{% block content %}
    <div class="container">
        <h1>Consultas</h1> <hr>
        <form method="GET">
            
            <div class="row pb-2">
                <div class="col">
                    <label for="{{form.socio_id.id_for_label}}">Socio ID:</label>
                    {{form.socio_id}}
                </div>
                <div class="col">
                    <label for="{{form.dni.id_for_label}}">DNI:</label>
                    {{form.dni}}
                </div>
                <div class="col">
                    <label for="{{form.apellido.id_for_label}}">Apellido:</label>
                    {{form.apellido}}
                </div>
                <div class="col">
                    <label for="{{form.nombre.id_for_label}}">Nombre:</label>
                    {{form.nombre}}
                </div>
                <div class="col">
                    <label for="{{form.estado.id_for_label}}">Estado:</label>
                    {{form.estado}}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Buscar</button>
            <button type="reset" class="btn btn-secondary" onclick="location.href='/socios/list/'">Reestablecer</button>
            <button type="button" class="btn btn-success" onclick="descargarExcel()">Descargar Excel</button>

        </form>
        <hr>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Socio ID</th>
                    <th>Apellido</th>
                    <th>Nombre</th>
                    <th>DNI</th>
                    <th>Estado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for socio in socios %}
                    <tr>
                        <td>{{socio.socio_id}}</td>
                        <td>{{socio.apellido}}</td>
                        <td>{{socio.nombre}}</td>
                        <td>{{socio.dni}}</td>
                        <td>
                            {% if socio.estado == 'A' %}
                                ACTIVO
                            {% elif socio.estado == 'S' %}
                                SUSPENDIDO
                            {% elif socio.estado == 'B' %}
                                BAJA
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'socios:socio_detail' socio.socio_id %}" class="btn btn-info">Ver</a>
                            <a href="{% url 'socios:socio_update' socio.socio_id %}" class="btn btn-success">Editar</a>
                            
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="container ">
        <nav aria-label="Page navigation" >
            <ul class="pagination justify-content-center">
            {% if socios.has_previous %}
                <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
                </li>
                <li class="page-item">
                <a class="page-link" href="?page={{ socios.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
                </li>
            {% endif %}
            {% for num in socios.paginator.page_range %}
                {% if socios.number == num %}
                <li class="page-item active"><span class="page-link">{{ num }}</span></li>
                {% elif num > socios.number|add:'-3' and num < socios.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}
            {% if socios.has_next %}
                <li class="page-item">
                <a class="page-link" href="?page={{ socios.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
                </li>
                <li class="page-item">
                <a class="page-link" href="?page={{ socios.paginator.num_pages }}" aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
                </li>
            {% endif %}
            </ul>
        </nav>
    </div>
    </div>
    <script>
        function descargarExcel() {
            // Construye la URL actual
            const urlActual = window.location.href;
            // Verifica si la URL ya tiene parámetros
            const tieneParametros = urlActual.includes('?');
            // Redirige al usuario, añadiendo el parámetro necesario para descargar el Excel
            window.location.href = urlActual + (tieneParametros ? '&formato=excel' : '?formato=excel');
        }
    </script>
{% endblock content %}
    
    

templates/login.html
{% extends 'base.html' %}

{% block content %}
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card " style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase">MU.SIN.JER</h2>
              <p></p>
              <form method="post" >
                {% csrf_token %}
              <div data-mdb-input-init class="form-group mb-4 text-start">
                <label class="form-label " for="username">Usuario</label>
                <input type="text" id="floatingInput" name="username" class="form-control form-control-lg" />
              </div>

              <div data-mdb-input-init class="form-group form-white mb-4 text-start">
                <label class="form-label" for="password">Password</label>
                <input type="password" id="password" name="password" class="form-control form-control-lg" />
              </div>

              

              <button data-mdb-button-init data-mdb-ripple-init class="btn btn-outline-dark btn-lg px-5" type="submit">Iniciar Sesión</button>
            </form>
             
            </div>

            

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/socio_detail.html
{% extends 'base.html' %}

{% block title %}
  <title>Detalle Socio</title>
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Detalle del Socio numero: {{ socio.socio_id }}</h1> <hr />
    {% if socio.caracter %}
      <p>
        <strong>Caracter:</strong>
        {{ socio.caracter }}
      </p>
    {% endif %}
    {% if socio.estado %}
      <p>
        <strong>Estado:</strong> 
        {% if socio.estado == 'A' %}
        ACTIVO
        {% elif socio.estado == 'S' %}
        SUSPENDIDO
        {% else %}
        BAJA
        {% endif %}
        
      </p>
    {% endif %}
    {% if socio.apellido %}
      <p>
        <strong>Apellido:</strong> {{ socio.apellido }}
      </p>
    {% endif %}
    {% if socio.nombre %}
      <p>
        <strong>Nombre:</strong> {{ socio.nombre }}
      </p>
    {% endif %}
    {% if socio.dni %}
      <p>
        <strong>DNI:</strong> {{ socio.dni }}
      </p>
    {% endif %}
    {% if socio.sexo %}
      <p>
        <strong>Sexo:</strong> {{ socio.sexo }}
      </p>
    {% endif %}
    {% if socio.fec_nac %}
      <p>
        <strong>Fecha de Nacimiento:</strong> {{ socio.fec_nac }}
      </p>
    {% endif %}
    {% if socio.estado_civil %}
      <p>
        <strong>Estado Civil:</strong> {{ socio.estado_civil }}
      </p>
    {% endif %}
    {% if socio.direccion %}
      <p>
        <strong>Dirección:</strong> {{ socio.direccion }}
      </p>
    {% endif %}
    {% if socio.localidad %}
      <p>
        <strong>Localidad:</strong> {{ socio.localidad }}
      </p>
    {% endif %}
    {% if socio.celular %}
      <p>
        <strong>Celular:</strong> {{ socio.celular }}
      </p>
    {% endif %}
    {% if socio.telefono %}
      <p>
        <strong>Teléfono:</strong> {{ socio.telefono }}
      </p>
    {% endif %}
    {% if socio.email %}
      <p>
        <strong>Email:</strong> {{ socio.email }}
      </p>
    {% endif %}
    {% if socio.dependencia %}
      <p>
        <strong>Dependencia:</strong> {{ socio.dependencia }}
      </p>
    {% endif %}
    {% if socio.cargo %}
      <p>
        <strong>Cargo:</strong> {{ socio.cargo }}
      </p>
    {% endif %}
    {% if socio.funcion %}
      <p>
        <strong>Función:</strong> {{ socio.funcion }}
      </p>
    {% endif %}
    {% if socio.domicilio_laboral %}
      <p>
        <strong>Domicilio Laboral:</strong> {{ socio.domicilio_laboral }}
      </p>
    {% endif %}
    {% if socio.telefono_laboral %}
      <p>
        <strong>Teléfono Laboral:</strong> {{ socio.telefono_laboral }}
      </p>
    {% endif %}

    {% if socio.grupo_set.all %}
      <h2>Grupo Familiar</h2> <hr />
      <ul>
        <table class="table table-sm">
          <thead>
            <tr>
              <th>DNI</th>
              <th>Apellido</th>
              <th>Nombre</th>
              <th>Parentesco</th>
            </tr>
          </thead>
          <tbody>
            {% for grupo in socio.grupo_set.all %}
              <tr>
                <td>{{ grupo.dni_familiar }}</td>
                <td>{{ grupo.apellido_familiar }}</td>
                <td>{{ grupo.nombre_familiar }}</td>
                <td>{{ grupo.parentesco }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </ul>
    {% endif %}

    <a class="btn btn-success" href="{% url 'socios:socio_update' socio_id=socio.socio_id %}">Editar</a>
    <a class="btn btn-primary" href="{% url 'socios:socio_create' %}">Crear Nuevo Socio</a>
    <a class="btn btn-danger" href="{% url 'socios:socio_delete' socio_id=socio.socio_id %}">Eliminar</a>
  </div>
{% endblock %}